
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('Starting Notice Test...');

    // 1. Find a user to be the author
    const user = await prisma.user.findFirst();
    if (!user) {
        console.log('❌ No user found to be author. Cannot create notice.');
        return;
    }
    console.log(`✅ Found user: ${user.email} (${user.id})`);

    // 2. Create a notice
    const noticeTitle = `Test Notice ${Date.now()}`;
    try {
        const notice = await prisma.notice.create({
            data: {
                title: noticeTitle,
                content: 'This is a test notice generated by the verification script.',
                authorId: user.id,
                audience: 'ALL',
                pinned: true
            }
        });
        console.log('✅ Created notice:', notice.id);
    } catch (error) {
        console.error('❌ Failed to create notice:', error);
        return;
    }

    // 3. Fetch notices
    try {
        const notices = await prisma.notice.findMany({
            where: { title: noticeTitle }
        });
        if (notices.length > 0 && notices[0].title === noticeTitle) {
            console.log('✅ Verified: Notice found in database.');
        } else {
            console.log('❌ Failed verification: Notice not found.');
        }
    } catch (error) {
        console.error('❌ Failed to fetch notices:', error);
    }
}

main()
    .catch(e => console.error(e))
    .finally(async () => {
        await prisma.$disconnect();
    });
